// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dagger from "jsr:@fluentci/sdk/dagger";

var output = await Dagger.dag.pipeline("demo").container().from("alpine:latest").withExec([
        "echo",
        "Hello, World!"
      ]).stdout();

console.log("Output: " + output);

export {
  output ,
}
/* output Not a pure module */
