// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sdk from "@fluentci/sdk";

var secret = Sdk.dag.setSecret("GITHUB", "my-github-token");

console.log(await secret.plaintext());

var secretDemo = await Sdk.dag.pipeline("secret-demo").withSecretVariable("GITHUB", secret).withExec(["echo $GITHUB"]).stdout();

console.log("Secret demo: " + secretDemo);

export {
  secret ,
  secretDemo ,
}
/* secret Not a pure module */
