description = "Write CI/CD pipelines in Gleam"
licences = ["MIT"]
links = [
  { title = "Website", href = "https://fluentci.io" },
  { title = "Sponsor", href = "https://github.com/sponsors/fluentci-io" },
]
name = "fluentci"
repository = { type = "github", user = "fluentci-io", repo = "fluentci-engine" }
target = "javascript"
version = "1.0.0"

[javascript]
runtime = "deno"
typescript_declarations = true

[javascript.deno]
allow_all = true

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_javascript = ">= 0.11.0 and < 1.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
