[package]
edition = "2021"
name = "nix"
version = "0.1.0"

[lib]
crate_type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extism-pdk = "1.1.0"
fluentci-client = {path = "../../crates/client", version = "0.1.0"}
