[package]
edition = "2021"
name = "flox"
version = "0.1.3"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extism-pdk = "1.1.0"
fluentci-pdk = {path = "../../crates/pdk", version = "0.2.0"}
