// Generated by ReScript, PLEASE EDIT WITH CARE


var CacheVolume = {};

var Port = {};

var Secret = {};

var EnvVariable = {};

var ModuleDependency = {};

var EnumValueTypeDef = {};

var EnumTypeDef = {};

var TypeDef = {};

var FieldTypeDef = {
  TypeDef: TypeDef
};

var InputTypeDef = {};

var TypeDef$1 = {};

var FunctionArg = {};

var $$Function = {};

var InterfaceTypeDef = {
  TypeDef: TypeDef$1,
  FunctionArg: FunctionArg,
  $$Function: $$Function
};

var TypeDef$2 = {};

var FunctionArg$1 = {};

var $$Function$1 = {};

var ObjectTypeDef = {
  TypeDef: TypeDef$2,
  FunctionArg: FunctionArg$1,
  $$Function: $$Function$1
};

var ScalarTypeDef = {};

var TypeDefKind = {};

var FunctionArg$2 = {};

var $$Function$2 = {};

var ListTypeDef = {};

var TypeDef$3 = {
  FunctionArg: FunctionArg$2,
  $$Function: $$Function$2,
  ListTypeDef: ListTypeDef
};

var Service = {};

var Socket = {};

var $$File = {};

var Container = {};

var Module = {};

var Directory = {
  Container: Container,
  Module: Module
};

var Host = {};

var GitRef = {};

var GitRepository = {};

var Label = {};

var ContainerExecOpts = {};

var Container$1 = {};

var ModuleSource = {};

var Module$1 = {};

var $$JSON = {};

var FunctionArg$3 = {};

var $$Function$3 = {};

var FunctionCallArgValue = {};

var FunctionCall = {};

var Client = {};

var $$Node = {};

var $$Bun = {};

var $$Deno = {};

export {
  CacheVolume ,
  Port ,
  Secret ,
  EnvVariable ,
  ModuleDependency ,
  EnumValueTypeDef ,
  EnumTypeDef ,
  FieldTypeDef ,
  InputTypeDef ,
  InterfaceTypeDef ,
  ObjectTypeDef ,
  ScalarTypeDef ,
  TypeDefKind ,
  TypeDef$3 as TypeDef,
  Service ,
  Socket ,
  $$File ,
  Directory ,
  Host ,
  GitRef ,
  GitRepository ,
  Label ,
  ContainerExecOpts ,
  Container$1 as Container,
  ModuleSource ,
  Module$1 as Module,
  $$JSON ,
  FunctionArg$3 as FunctionArg,
  $$Function$3 as $$Function,
  FunctionCallArgValue ,
  FunctionCall ,
  Client ,
  $$Node ,
  $$Bun ,
  $$Deno ,
}
/* No side effect */
