// Generated by ReScript, PLEASE EDIT WITH CARE


var NixArgs = {};

var Cache = {};

var Service = {};

var Secret = {};

var Devbox = {};

var Devenv = {};

var Envhub = {};

var Flox = {};

var Mise = {};

var Nix = {};

var Pixi = {};

var Pkgx = {};

var Directory = {};

var $$File = {
  Directory: Directory
};

var Directory$1 = {};

var Git = {};

var Pipeline = {};

var SecretManager = {};

var Client = {};

var $$Node = {};

var $$Bun = {};

var $$Deno = {};

export {
  NixArgs ,
  Cache ,
  Service ,
  Secret ,
  Devbox ,
  Devenv ,
  Envhub ,
  Flox ,
  Mise ,
  Nix ,
  Pixi ,
  Pkgx ,
  $$File ,
  Directory$1 as Directory,
  Git ,
  Pipeline ,
  SecretManager ,
  Client ,
  $$Node ,
  $$Bun ,
  $$Deno ,
}
/* No side effect */
