name: ci
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v4
      - name: Run Dagger Pipelines
        run: |
          fluentci run rust_pipeline build
          ls -ltr target
          rm -rf target/release/build target/release/deps target/release/examples target/release/incremental
          fluentci run . e2e
        env:
          PACKAGE_NAME: fluentci-engine
          FLUENTCI_ENGINE_HOST: 0.0.0.0
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
