name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          pipeline: rust
          args: build --release
      - name: Run Build and e2e tests
        run: |
          export PATH=${HOME}/.cargo/bin:${PATH}
          ls -ltr target
          rm -rf target/release/build target/release/deps target/release/examples target/release/incremental
          sudo cp target/release/fluentci-engine /usr/local/bin
          fluentci-engine run -- deno run -A ../.fluentci/e2e.ts
        working-directory: fixtures
        env:
          FLUENTCI_CACHE_CDN_ENDPOINT: https://cache.fluentci.io
          FLUENTCI_CACHE_S3_ENDPOINT: https://fe5b1e2ce9f94f4c0415ab94ce402012.r2.cloudflarestorage.com
          FLUENTCI_CACHE_S3_BUCKET: cache
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
          HONEYCOMB_DATASET: fluentci-engine
          OTEL_EXPORTER_OTLP_ENDPOINT: https://api.honeycomb.io
          BASELIME_API_KEY: ${{ secrets.BASELIME_API_KEY }}

  publish:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41
      - name: Publish package
        run: deno publish --allow-slow-types
        working-directory: ./sdk/typescript
