name: ci
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v4
      - name: Run Build and e2e tests
        run: |
          fluentci run rust_pipeline build
          ls -ltr target
          rm -rf target/release/build target/release/deps target/release/examples target/release/incremental
          fluentci run . e2e
        env:
          PACKAGE_NAME: fluentci-engine
          WORK_DIR: ./fixtures
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
  publish:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41
      - name: Publish package
        run: deno publish --allow-slow-types
        working-directory: ./sdk/typescript
